### ISSUE TITLE
Issue with Kinect for Windows on Windows 10

### ISSUE THREAD

**Issue by olprofesur** [enauman/CANKinectPhysics#1]
Hi,
I tried this code on the following environment:

Windows 10 64bit
Kinect for Windows (driver installed with libusbK 3.0.6 using Zodag 2.0.1)
Processing 3.4

Unfortunately something does not work: I can't see my body but a strange large triangle instead; I remember the wonderful behavior with Processing 2, with this code on my environment I cant'see it.

Best,
Diego

**Comment by enauman** [comment]
Does the kinect work with an openkinect example sketch? If it does and it something in the sketch it could be calibration, adjust the minThresh and maxThresh values, make sure it's not detecting objects in the periphery, the area needs to be clear, and maybe tilted up so it doesn't detect the floor. I don't have a Windows computer but it's working well on Mac 10.13 with Processing 3.4. I'm using Kinect XBox 360 and Kinect for Windows.

**Comment by olprofesur** [comment]
Actually, because of the urgency of the activity, I "solved" installing
Processing 2 and SimpleOpenNI in order to run the original program.

I will check in next days and I will update you.
The examples of openkinect worked; however I installed the "original"
Microsoft driver instead of the ones from Zadig, may be this will solve the
issue.

Diego

Il giorno mer 31 ott 2018 alle ore 03:02 enauman <notifications@github.com>
ha scritto:

**Comment by enauman** [comment]
Sorry late to answer. I cannot test on Windows so it's helpful you are testing proper driver setup. On Mac no driver needs to be installed.
